import { useState } from "react";
import { usePostCategory } from "../../hooks/useCategories";

function PostCategory() {

  const [categoryName, setCategoryName] = useState("");
  const createCategory = usePostCategory();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!categoryName.trim()) return;
    try {
      await createCategory.mutateAsync({
        categoryName: categoryName.trim(),
      });
      setCategoryName("");
      console.log("Category created successfully!");
    } catch (error) {
      console.error("Failed to create category: ", error);
    }
  };

  const handleInputChange = (e) => {
    setCategoryName(e.target.value);
  };

  return (
    <div className="category">
      <h1>📦 Create Category</h1>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          disabled
          placeholder="Category ID will be auto-generated by the system..."
        />
        <input
          type="text"
          name="categoryName"
          value={categoryName}
          onChange={handleInputChange}
          placeholder="Enter category name..."
        />
        <button
          type="submit"
          disabled={createCategory.isPending || !categoryName.trim()}
        >
          {createCategory.isPending ? "Creating..." : "Create Category"}
        </button>
      </form>

      {createCategory.isSuccess && (
        <div className="category-details">
          <h1>Category Details</h1>
          <p>✅ Category created successfully!</p>
          {createCategory.data && (
            <p>
              Created: {createCategory.data.categoryName} (ID:{" "}
              {createCategory.data.categoryID})
            </p>
          )}
        </div>
      )}

      {createCategory.isError && (
        <div className="category-error">
          <h1>Category error</h1>
          <p>
            Error in creating category :{" "}
            {createCategory.error?.response?.data ||
              createCategory.error?.message}
          </p>
        </div>
      )}
    </div>
  );
}

export default PostCategory;
